project:
  type: website

website:
  title: "William's Simple Geode"
  favicon: ~/is415-gaa-williamtjw/pompom.jpeg
  image: ~/is415-gaa-williamtjw/pompom.jpeg
  navbar:
    logo: 'pompom.jpeg'
    search: true
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "resources/Hands-on_Ex/ex1/Hands-On_Ex_1.qmd"
        - text: "Hands-on Exercise 2"
          href: "resources/Hands-on_Ex/ex2/Hands-On_Ex_2.qmd"
        - text: "Hands-on Exercise 3"
          href: "resources/Hands-on_Ex/ex3/Hands-On_Ex_3.qmd"
        - text: "Hands-on Exercise 4"
          href: "resources/Hands-on_Ex/ex4/Hands-On_Ex_4.qmd"  
        - text: "Hands-on Exercise 5"
          href: "resources/Hands-on_Ex/ex5/Hands-On_Ex_5.qmd"
        - text: "Hands-on Exercise 6"
          href: "resources/Hands-on_Ex/ex6/Hands-On_Ex_6.qmd"
        - text: "Hands-on Exercise 7"
          href: "resources/Hands-on_Ex/ex7/Hands-On_Ex_7.qmd"
        - text: "Hands-on Exercise 9"
          href: "resources/Hands-on_Ex/ex9/Hands-On_Ex_9.qmd"
        - text: "Hands-on Exercise 10"
          href: "resources/Hands-on_Ex/ex10/Hands-On_Ex10_1.qmd"
        - text: "Hands-on Exercise 11"
          href: "resources/Hands-on_Ex/ex11/Hands-On_Ex_11.qmd"
        - text: "Hands-on Exercise 12"
          href: "resources/Hands-on_Ex/ex12/Hands-On_Ex_12.qmd"
          
    - text: "In-class Exercise (ICE)"
      menu:
        - text: "ICE 1"
          href: "resources/ICEs/ex1/ice1.qmd"
        - text: "ICE 2"
          href: "resources/ICEs/ex2/ice2.qmd" 
        - text: "ICE 3"
          href: "resources/ICEs/ex3/ice3.qmd"
        - text: "ICE 4"
          href: "resources/ICEs/ex4/ice4.qmd"
        - text: "ICE 5"
          href: "resources/ICEs/ex5/ice5.qmd"
        - text: "ICE 6"
          href: "resources/ICEs/ex6/ice6.qmd"
        - text: "ICE 7"
          href: "resources/ICEs/ex7/ice7.qmd"
        - text: "ICE 9"
          href: "resources/ICEs/ex9/ice9.qmd"
          
    - text: "Take-home Exercise (THE)"
      menu:
        - text: "Take-home Exercise 1"
          href: "resources/Take-home_Ex/ex1/Take-home_Ex_1.qmd"
        - text: "Take-home Exercise 2"
          href: "resources/Take-home_Ex/ex2/Take-home_Ex_2.qmd"
        - text: "Take-home Exercise 3"
          href: "resources/Take-home_Ex/ex3/Take-home_Ex_3.qmd"
          
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

