project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "resources/Hands-on_Ex/ex1/Hands-On_Ex_1.qmd"
        - text: "Hands-on Exercise 2"
          href: "resources/Hands-on_Ex/ex2/Hands-On_Ex_2.qmd"
        - text: "Hands-on Exercise 3"
          href: "resources/Hands-on_Ex/ex3/Hands-On_Ex_3.qmd"          
          
    - text: "In-class Exercise (ICE)"
      menu:
        - text: "ICE 1"
          href: "resources/ICEs/ex1/ice1.qmd"
        - text: "ICE 2"
          href: "resources/ICEs/ex2/ice2.qmd" 
          text: "ICE 3"
          href: "resources/ICEs/ex3/ice3.qmd"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

